# Generated by Django 6.0.3 on 2026-03-20 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monitor',
            old_name='especialidad',
            new_name='clases',
        ),
    ]
