# Generated by Django 6.0.3 on 2026-05-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasio', '0002_rename_especialidad_monitor_clases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='horario',
            field=models.TextField(),
        ),
    ]
